### ISSUE TITLE
Fail to use curl to register device

### ISSUE THREAD

**Issue by topfs2** [yene/nupnp#1]
```
tobias@tobias-XPS-15-9560:~$ curl -i -H "Content-Type: application/json" -X POST -d '{"name":"Devicename","address":"192.168.1.64"}' https://nupnp.com/api/register
HTTP/2 301 
location: https://www.nupnp.com
server: Caddy
content-type: text/plain; charset=utf-8
content-length: 0
date: Tue, 15 May 2018 19:22:25 GMT
```

If I checkout and run the code locally

```
tobias@tobias-XPS-15-9560:~$ curl -i -H "Content-Type: application/json" -X POST -d '{"name":"Devicename","address":"192.168.1.64"}' http://localhost:8180/api/register
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 15 May 2018 19:21:43 GMT
Content-Length: 69

Host 127.0.0.1 is not allowed to register devices
404 page not found
```

If I use the fetch API in a browser it does work however, but cURL and node-fetch (fetch in nodejs) doesn't

**Comment by yene** [comment]
hmm, it works on mac osx.
`X-Content-Type-Options: nosniff` tells me that in your setup something is different.
Do you use a proxy,  or a very strong firewall/antivirus?

**Comment by topfs2** [comment]
Sorry for slow response

I have a normal home internet, computer -> router -> fibre. Shouldn't be proxying anything odd I would think?

As far as I can tell I get the same error when doing the request via node too, so it isn't isolated to curl, it was mostly easiest to share. I can share a node example if it would help though?

I am running Ubuntu 18.04, I noticed you mentioning Raspberry Pi on your site, what OS does that work on? perhaps I can install the aame on my raspberry to verify my internet?

**Comment by yene** [comment]
Remove the proxy check and you are good to go https://github.com/yene/nupnp/blob/master/main.go#L113

**Comment by topfs2** [comment]
Sure can do.

Just found it odd that it works in Firefox but not in node or curl
